AWSTemplateFormatVersion: '2010-09-09'
Resources:
  APIGatewayCloudWatchRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: APIGatewayCloudWatchRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - apigateway.amazonaws.com
            Action: 
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
  
  ApiGatewayAccount:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt APIGatewayCloudWatchRole.Arn
      
Outputs:
  APIGatewayCloudWatchRoleArn:
    Description: "API Gateway CloudWatch Logging Role ARN"
    Value: !GetAtt APIGatewayCloudWatchRole.Arn
