AWSTemplateFormatVersion: '2010-09-09'

Resources:
  PersonTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "OneHundredLettersPersonTable"
      AttributeDefinitions:
        - AttributeName: "PK"
          AttributeType: "S"
        - AttributeName: "SK"
          AttributeType: "S"
        - AttributeName: "firstName"
          AttributeType: "S"
        - AttributeName: "lastName"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "PK"
          KeyType: "HASH"
        - AttributeName: "SK"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      BillingMode: PROVISIONED
      Tags:
        - Key: "Name"
          Value: "OneHundredLettersPersonTable"
      GlobalSecondaryIndexes:
        - IndexName: "LastNameIndex"
          KeySchema:
            - AttributeName: "lastName"
              KeyType: "HASH"
            - AttributeName: "firstName"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  CorrespondenceTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "OneHundredLettersCorrespondenceTable"
      AttributeDefinitions:
        - AttributeName: "PK"
          AttributeType: "S"
        - AttributeName: "SK"
          AttributeType: "S"
        - AttributeName: "createdAt"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "PK"
          KeyType: "HASH"
        - AttributeName: "SK"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      BillingMode: PROVISIONED
      Tags:
        - Key: "Name"
          Value: "OneHundredLettersCorrespondenceTable"
      GlobalSecondaryIndexes:
        - IndexName: "CreatedAtIndex"
          KeySchema:
            - AttributeName: "PK"
              KeyType: "HASH"
            - AttributeName: "createdAt"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  LetterTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "OneHundredLettersLetterTable"
      AttributeDefinitions:
        - AttributeName: "PK"
          AttributeType: "S"
        - AttributeName: "SK"
          AttributeType: "S"
        - AttributeName: "status"
          AttributeType: "S"
        - AttributeName: "date"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "PK"
          KeyType: "HASH"
        - AttributeName: "SK"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      BillingMode: PROVISIONED
      Tags:
        - Key: "Name"
          Value: "OneHundredLettersLetterTable"
      GlobalSecondaryIndexes:
        - IndexName: "LetterStatusIndex"
          KeySchema:
            - AttributeName: "status"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
        - IndexName: "LetterDateIndex"
          KeySchema:
            - AttributeName: "PK"
              KeyType: "HASH"
            - AttributeName: "date"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

Outputs:
  PersonTable:
    Value: !Ref PersonTable
    Description: "DynamoDB table for Person"
  CorrespondenceTable:
    Value: !Ref CorrespondenceTable
    Description: "DynamoDB table for Correspondence"
  LetterTable:
    Value: !Ref LetterTable
    Description: "DynamoDB table for Letter"
