AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Environment:
    Type: String
    Default: "dev"
    Description: "The environment for the deployment (dev or prod)"
    AllowedValues:
      - dev
      - prod
    ConstraintDescription: "Must be either 'dev' or 'prod'."
  LambdaS3BucketName:
    Type: String
    Default: "100-letters-project-api"
    Description: "S3 bucket for storing Lambda deployment packages"

Resources:
  LambdaDeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${LambdaS3BucketName}-${Environment}"

Outputs:
  BucketName:
    Value: !Ref LambdaDeploymentBucket
    Export:
      Name: !Sub "${LambdaS3BucketName}-${Environment}"
