AWSTemplateFormatVersion: '2010-09-09'

Resources:
  # <------------------- Shared Components ------------------->

  AddressSchema:
    Type: AWS::ApiGateway::Model
    Properties:
      RestApiId: !ImportValue OneHundredLettersApi
      ContentType: "application/json"
      Name: "AddressSchema"
      Schema:
        $schema: "http://json-schema.org/draft-04/schema#"
        type: "object"
        properties:
          city:
            type: "string"
          country:
            type: "string"
          postalCode:
            type: "string"
          state:
            type: "string"
          street:
            type: "string"

  RecipientSchema:
    Type: AWS::ApiGateway::Model
    Properties:
      RestApiId: !ImportValue OneHundredLettersApi
      ContentType: "application/json"
      Name: "RecipientSchema"
      Schema:
        $schema: "http://json-schema.org/draft-04/schema#"
        type: "object"
        properties:
          address:
            $ref: !Ref AddressSchema
          firstName:
            type: "string"
          lastName:
            type: "string"
          description:
            type: "string"
          occupation:
            type: "string"
          organization:
            type: "string"
        required: ["address", "firstName", "lastName"]

  # <------------------- CREATE Recipients ------------------->

  RecipientCreateRequestModel:
    Type: AWS::ApiGateway::Model
    Properties:
      RestApiId: !ImportValue OneHundredLettersApi
      ContentType: "application/json"
      Name: "RecipientCreateModel"
      Schema:
        $schema: "http://json-schema.org/draft-04/schema#"
        type: "object"
        allOf:
          - $ref: !Ref RecipientSchema

  RecipientCreateResponseModel:
    Type: AWS::ApiGateway::Model
    Properties:
      RestApiId: !ImportValue OneHundredLettersApi
      ContentType: "application/json"
      Name: "RecipientCreateResponseModel"
      Schema:
        $schema: "http://json-schema.org/draft-04/schema#"
        type: "object"
        properties:
          data:
            type: "object"
            allOf:
              - $ref: !Ref RecipientSchema
              - properties:
                  recipientId:
                    type: "string"
            required: ["recipientId"]
          message:
            type: string
        required: ["data", "message"]
        
  # <------------------- UPDATE Recipients ------------------->

  RecipientUpdateRequestModel:
    Type: AWS::ApiGateway::Model
    Properties:
      RestApiId: !ImportValue OneHundredLettersApi
      ContentType: "application/json"
      Name: "RecipientUpdateRequestModel"
      Schema:
        $schema: "http://json-schema.org/draft-04/schema#"
        type: "object"
        properties:
          recipientId:
            type: "string"
          allOf:
            - $ref: !Ref RecipientSchema
        required: ["recipientId"]
  
  RecipientUpdateResponseModel:
    Type: AWS::ApiGateway::Model
    Properties:
      RestApiId: !ImportValue OneHundredLettersApi
      ContentType: "application/json"
      Name: "RecipientUpdateResponseModel"
      Schema:
        $schema: "http://json-schema.org/draft-04/schema#"
        type: "object"
        properties:
          data:
            type: "object"
            allOf:
              - $ref: !Ref RecipientSchema
              - properties:
                  recipientId:
                    type: "string"
            required: ["recipientId"]
          message:
            type: string
        required: ["data", "message"]

  # <------------------- GET Recipients ------------------->

  RecipientResponseModel:
    Type: AWS::ApiGateway::Model
    Properties:
      RestApiId: !ImportValue OneHundredLettersApi
      ContentType: "application/json"
      Name: "RecipientResponseModel"
      Schema:
        $schema: "http://json-schema.org/draft-04/schema#"
        type: "object"
        properties:
          data:
            type: "array"
            items:
              allOf:
                - type: "object"
                  properties:
                    recipientId:
                      type: "string"
                - $ref: !Ref RecipientSchema
          lastEvaluatedKey:
            type: "string"
        required: ["data", "lastEvaluatedKey"]

  # <------------------- GET Recipients By ID ------------------->

  RecipientByIdResponseModel:
    Type: AWS::ApiGateway::Model
    Properties:
      RestApiId: !ImportValue OneHundredLettersApi
      ContentType: "application/json"
      Name: "RecipientByIdResponseModel"
      Schema:
        $schema: "http://json-schema.org/draft-04/schema#"
        type: "object"
        properties:
          data:
            type: "object"
            allOf:
              - $ref: !Ref RecipientSchema
              - properties:
                  recipientId:
                    type: "string"
            required: ["recipientId"]
        required: ["data"]

  # <------------------- DELETE Recipients ------------------->

  RecipientDeleteResponseModel:
    Type: AWS::ApiGateway::Model
    Properties:
      RestApiId: !ImportValue OneHundredLettersApi
      ContentType: "application/json"
      Name: "RecipientDeleteResponseModel"
      Schema:
        $schema: "http://json-schema.org/draft-04/schema#"
        type: "object"
        properties:
          data:
            type: "object"
            properties:
              recipientId:
                type: "string"
            required: ["recipientId"]
        required: ["data"]

Outputs:
  RecipientCreateRequestModelOutput:
    Value: !Ref RecipientCreateRequestModel
    Export:
      Name: RecipientCreateRequestModel
  RecipientUpdateRequestModelOutput:
    Value: !Ref RecipientUpdateRequestModel
    Export:
      Name: RecipientUpdateRequestModel
  RecipientResponseModelOutput:
    Value: !Ref RecipientResponseModel
    Export:
      Name: RecipientResponseModel
  RecipientCreateResponseModelOutput:
    Value: !Ref RecipientCreateResponseModel
    Export:
      Name: RecipientCreateResponseModel
  RecipientUpdateResponseModelOutput:
    Value: !Ref RecipientUpdateResponseModel
    Export:
      Name: RecipientUpdateResponseModel
  RecipientByIdResponseModelOutput:
    Value: !Ref RecipientByIdResponseModel
    Export:
      Name: RecipientByIdResponseModel
  RecipientDeleteResponseModelOutput:
    Value: !Ref RecipientDeleteResponseModel
    Export:
      Name: RecipientDeleteResponseModel
