AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  UserPoolId:
    Type: String
    Description: Cognito User Pool ID

Resources:
  OneHundredLettersApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: OneHundredLettersApi
      Description: API for managing correspondence and recipients

  ApiGatewayAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      Name: CognitoAuthorizer
      Type: COGNITO_USER_POOLS
      RestApiId: !Ref OneHundredLettersApi
      IdentitySource: method.request.header.Authorization
      ProviderARNs:
        - !Sub "arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${UserPoolId}"

  ApiGatewayExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole

  ApiGatewayPolicyAttachment:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: ApiGatewayAccessPolicy
      Roles:
        - !Ref ApiGatewayExecutionRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: 'execute-api:Invoke'
            Resource: !Sub "arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${OneHundredLettersApi}/*/*/*"
            Condition:
              StringEquals:
                aws:UserAgent: 'Amazon CloudFront'
  
  ApiGatewayCorrespondence:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref OneHundredLettersApi
      ParentId: !GetAtt OneHundredLettersApi.RootResourceId
      PathPart: "correspondence"
      
  ApiGatewayGetCorrespondencesMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref OneHundredLettersApi
      ResourceId: !Ref ApiGatewayCorrespondence
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: GET
        Type: AWS_PROXY
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:getCorrespondences/invocations"

  # ApiGatewayCorrespondenceUpdateMethod:
  #   Type: AWS::ApiGateway::Method
  #   Properties:
  #     RestApiId: !Ref OneHundredLettersApi
  #     ResourceId: !Ref ApiGatewayCorrespondence
  #     AuthorizationType: COGNITO_USER_POOLS
  #     AuthorizerId: !Ref ApiGatewayAuthorizer
  #     HttpMethod: PUT
  #     Integration:
  #       IntegrationHttpMethod: PUT
  #       Type: AWS_PROXY
  #       Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:updateCorrespondence/invocations"
      

  # ApiGatewayCorrespondenceCreateMethod:
  #   Type: AWS::ApiGateway::Method
  #   Properties:
  #     RestApiId: !Ref OneHundredLettersApi
  #     ResourceId: !Ref ApiGatewayCorrespondence
  #     AuthorizationType: COGNITO_USER_POOLS
  #     AuthorizerId: !Ref ApiGatewayAuthorizer
  #     HttpMethod: POST
  #     Integration:
  #       IntegrationHttpMethod: POST
  #       Type: AWS_PROXY
  #       Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:createCorrespondence/invocations"

  # ApiGatewayGetCorrespondencesById:
  #   Type: AWS::ApiGateway::Resource
  #   Properties:
  #     RestApiId: !Ref OneHundredLettersApi
  #     ParentId: !Ref ApiGatewayCorrespondence  # Corrected this line
  #     PathPart: "correspondence/{id}"
      
  # ApiGatewayGetCorrespondencesByIdMethod:
  #   Type: AWS::ApiGateway::Method
  #   Properties:
  #     RestApiId: !Ref OneHundredLettersApi
  #     ResourceId: !Ref ApiGatewayGetCorrespondencesById
  #     HttpMethod: GET
  #     Integration:
  #       IntegrationHttpMethod: GET
  #       Type: AWS_PROXY
  #       Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:getCorrespondencesById/invocations"

  # ApiGatewayGetRecipientById:
  #   Type: AWS::ApiGateway::Resource
  #   Properties:
  #     RestApiId: !Ref OneHundredLettersApi
  #     ParentId: !Ref ApiGatewayCorrespondence  # Corrected this line
  #     PathPart: "recipient/{id}"

  # ApiGatewayGetRecipientByIdMethod:
  #   Type: AWS::ApiGateway::Method
  #   Properties:
  #     RestApiId: !Ref OneHundredLettersApi
  #     ResourceId: !Ref ApiGatewayGetRecipientById
  #     HttpMethod: GET
  #     Integration:
  #       IntegrationHttpMethod: GET
  #       Type: AWS_PROXY
  #       Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:getRecipientById/invocations"

  # ApiGatewayGetRecipients:
  #   Type: AWS::ApiGateway::Resource
  #   Properties:
  #     RestApiId: !Ref OneHundredLettersApi
  #     ParentId: !Ref ApiGatewayCorrespondence  # Corrected this line
  #     PathPart: "recipient"

  # ApiGatewayGetRecipientsMethod:
  #   Type: AWS::ApiGateway::Method
  #   Properties:
  #     RestApiId: !Ref OneHundredLettersApi
  #     ResourceId: !Ref ApiGatewayGetRecipients
  #     HttpMethod: GET
  #     Integration:
  #       IntegrationHttpMethod: GET
  #       Type: AWS_PROXY
  #       Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:getRecipients/invocations"
