AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  UserPoolId:
    Type: String
    Description: Cognito User Pool ID

Resources:
  OneHundredLettersApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: OneHundredLettersApi
      Description: API for managing correspondence and letters

  OneHundredLettersValidator:
    Type: AWS::ApiGateway::RequestValidator
    Properties:
      RestApiId: !Ref OneHundredLettersApi
      Name: "RequestValidator"
      ValidateRequestBody: true
      ValidateRequestParameters: false

  OneHundredLettersAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      Name: CognitoAuthorizer
      Type: COGNITO_USER_POOLS
      RestApiId: !Ref OneHundredLettersApi
      IdentitySource: method.request.header.Authorization
      ProviderARNs:
        - !Sub "arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${UserPoolId}"

  # Correspondence Resources

  CorrespondenceResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref OneHundredLettersApi
      ParentId: !GetAtt OneHundredLettersApi.RootResourceId
      PathPart: "correspondence"
      
  CorrespondenceByIdResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref OneHundredLettersApi
      ParentId: !Ref CorrespondenceResource
      PathPart: "{id}"
      
  # Recipient Resources

  RecipientsResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref OneHundredLettersApi
      ParentId: !GetAtt OneHundredLettersApi.RootResourceId
      PathPart: "recipient"

  RecipientByIdResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref OneHundredLettersApi
      ParentId: !Ref RecipientsResource
      PathPart: "{id}"

  # Letter Resources

  LettersResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref OneHundredLettersApi
      ParentId: !GetAtt OneHundredLettersApi.RootResourceId
      PathPart: "letter"

  LetterByIdResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref OneHundredLettersApi
      ParentId: !Ref LettersResource
      PathPart: "{id}"

Outputs:
  ApiGatewayUrl:
    Value: !Sub "https://${OneHundredLettersApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
    Description: "URL of the deployed API Gateway"
  OneHundredLettersApiOutput:
    Value: !Ref OneHundredLettersApi
    Export:
      Name: OneHundredLettersApi
  OneHundredLettersValidatorOutput:
    Value: !Ref OneHundredLettersValidator
    Export:
      Name: OneHundredLettersValidator
  OneHundredLettersAuthorizerOutput:
    Value: !Ref OneHundredLettersAuthorizer
    Export:
      Name: OneHundredLettersAuthorizer
  CorrespondenceResourceOutput:
    Value: !Ref CorrespondenceResource
    Export:
      Name: CorrespondenceResource
  CorrespondenceByIdResourceOutput:
    Value: !Ref CorrespondenceByIdResource
    Export:
      Name: CorrespondenceByIdResource
  RecipientsResourceOutput:
    Value: !Ref RecipientsResource
    Export:
      Name: RecipientsResource
  RecipientByIdResourceOutput:
    Value: !Ref RecipientByIdResource
    Export:
      Name: RecipientByIdResource
  LettersResourceOutput:
    Value: !Ref LettersResource
    Export:
      Name: LettersResource
  LetterByIdResourceOutput:
    Value: !Ref LetterByIdResource
    Export:
      Name: LetterByIdResource