Resources:
  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GitHubActionsRole
      MaxSessionDuration: 14400  # 4 hours
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:user/Administrator
            Action:
              - sts:AssumeRole
              - sts:TagSession
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - sts:AssumeRole

  GitHubActionsRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: GitHubActionsPolicy
      Roles:
        - Ref: GitHubActionsRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:DeleteObject
              - s3:ListBucket
            Resource:
              - arn:aws:s3:::100-letters-project-api
              - arn:aws:s3:::100-letters-project-api/*

          - Effect: Allow
            Action:
              - lambda:CreateFunction
              - lambda:UpdateFunctionCode
              - lambda:GetFunction
              - lambda:ListFunctions
              - lambda:TagResource
            Resource:
              - !Sub arn:aws:lambda:us-west-2:${AWS::AccountId}:function:*

          - Effect: Allow
            Action:
              - iam:PassRole
            Resource:
              - !Sub arn:aws:iam::${AWS::AccountId}:role/OneHundredLettersLambdaRole
          
          - Effect: Allow
            Action:
              - cloudformation:DescribeStacks
              - cloudformation:CreateStack
              - cloudformation:UpdateStack
              - cloudformation:CreateChangeSet
              - cloudformation:DescribeChangeSet
              - cloudformation:ExecuteChangeSet
            Resource: 
              - !Sub "arn:aws:cloudformation:us-west-2:${AWS::AccountId}:stack/one-hundred-letters-route-*/*"
              
          - Effect: Allow
            Action:
              - lambda:AddPermission
            Resource:
              - !Sub "arn:aws:lambda:us-west-2:${AWS::AccountId}:function:*"

Outputs:
  GitHubActionsRole:
    Description: "GitHub Actions Role"
    Value: !Ref GitHubActionsRole

  GitHubActionsPolicy:
    Description: "GitHub Actions Policy"
    Value: !Ref GitHubActionsRolePolicy
