AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Environment:
    Type: String
    Default: "dev"
    Description: "The environment for the deployment (dev or prod)"
    AllowedValues:
      - dev
      - prod
    ConstraintDescription: "Must be either 'dev' or 'prod'."

Mappings:
  EnvCapitalization:
    dev:
      Capitalized: "Dev"
    prod:
      Capitalized: "Prod"

Resources:
  # <------------------- CREATE Recipient ------------------->

  RecipientCreateRequestModel:
    Type: AWS::ApiGateway::Model
    Properties:
      RestApiId: 
        Fn::ImportValue: 
          !Sub "one-hundred-letters-api-${Environment}"
      ContentType: "application/json"
      Name: !Sub 
        - "RecipientCreateRequestModel${CapitalizedEnv}"
        - CapitalizedEnv: !FindInMap [EnvCapitalization, !Ref Environment, Capitalized]
      Schema:
        $schema: "http://json-schema.org/draft-04/schema#"
        type: "object"
        properties:
          address:
            type: "object"
            properties:
              city:
                type: "string"
              country:
                type: "string"
              postalCode:
                type: "string"
              state:
                type: "string"
              street:
                type: "string"
            required: ["city", "country", "postalCode", "state", "street"]
          firstName:
            type: "string"
          lastName:
            type: "string"
          description:
            type: "string"
          occupation:
            type: "string"
          organization:
            type: "string"
        required: ["address", "firstName", "lastName"]

  RecipientCreateResponseModel:
    Type: AWS::ApiGateway::Model
    Properties:
      RestApiId: 
        Fn::ImportValue: 
          !Sub "one-hundred-letters-api-${Environment}"
      ContentType: "application/json"
      Name: !Sub 
        - "RecipientCreateResponseModel${CapitalizedEnv}"
        - CapitalizedEnv: !FindInMap [EnvCapitalization, !Ref Environment, Capitalized]
      Schema:
        $schema: "http://json-schema.org/draft-04/schema#"
        type: "object"
        properties:
          data:
            type: "object"
            properties:
              recipientId:
                type: "string"
                format: "uuid"
              address:
                type: "object"
                properties:
                  city:
                    type: "string"
                  country:
                    type: "string"
                  postalCode:
                    type: "string"
                  state:
                    type: "string"
                  street:
                    type: "string"
                required: ["city", "country", "postalCode", "state", "street"]
              createdAt:
                type: "string"
                format: "date-time"
              firstName:
                type: "string"
              lastName:
                type: "string"
              description:
                type: "string"
              occupation:
                type: "string"
              organization:
                type: "string"
              updatedAt:
                type: "string"
                format: "date-time"
            required: ["address", "createdAt", "firstName", "lastName", "recipientId", "updatedAt"]
          message:
            type: string
        required: ["data", "message"]
        
  # <------------------- UPDATE Recipient ------------------->

  RecipientUpdateRequestModel:
    Type: AWS::ApiGateway::Model
    Properties:
      RestApiId: 
        Fn::ImportValue: 
          !Sub "one-hundred-letters-api-${Environment}"
      ContentType: "application/json"
      Name: !Sub 
        - "RecipientUpdateRequestModel${CapitalizedEnv}"
        - CapitalizedEnv: !FindInMap [EnvCapitalization, !Ref Environment, Capitalized]
      Schema:
        $schema: "http://json-schema.org/draft-04/schema#"
        type: "object"
        properties:
          recipientId:
            type: "string"
            format: "uuid"
          address:
            type: "object"
            properties:
              city:
                type: "string"
              country:
                type: "string"
              postalCode:
                type: "string"
              state:
                type: "string"
              street:
                type: "string"
            required: ["city", "country", "postalCode", "state", "street"]
          firstName:
            type: "string"
          lastName:
            type: "string"
          description:
            type: "string"
          occupation:
            type: "string"
          organization:
            type: "string"
        required: ["address", "firstName", "lastName", "recipientId"]

  RecipientUpdateResponseModel:
    Type: AWS::ApiGateway::Model
    Properties:
      RestApiId: 
        Fn::ImportValue: 
          !Sub "one-hundred-letters-api-${Environment}"
      ContentType: "application/json"
      Name: !Sub 
        - "RecipientUpdateResponseModel${CapitalizedEnv}"
        - CapitalizedEnv: !FindInMap [EnvCapitalization, !Ref Environment, Capitalized]
      Schema:
        $schema: "http://json-schema.org/draft-04/schema#"
        type: "object"
        properties:
          data:
            type: "object"
            properties:
              recipientId:
                type: "string"
                format: "uuid"
              address:
                type: "object"
                properties:
                  city:
                    type: "string"
                  country:
                    type: "string"
                  postalCode:
                    type: "string"
                  state:
                    type: "string"
                  street:
                    type: "string"
                required: ["city", "country", "postalCode", "state", "street"]
              createdAt:
                type: "string"
                format: "date-time"
              firstName:
                type: "string"
              lastName:
                type: "string"
              description:
                type: "string"
              occupation:
                type: "string"
              organization:
                type: "string"
              updatedAt:
                type: "string"
                format: "date-time"
            required: ["address", "createdAt", "firstName", "lastName", "recipientId", "updatedAt"]
          message:
            type: string
        required: ["data", "message"]

  # <------------------- GET Recipients ------------------->

  RecipientResponseModel:
    Type: AWS::ApiGateway::Model
    Properties:
      RestApiId: 
        Fn::ImportValue: 
          !Sub "one-hundred-letters-api-${Environment}"
      ContentType: "application/json"
      Name: !Sub 
        - "RecipientResponseModel${CapitalizedEnv}"
        - CapitalizedEnv: !FindInMap [EnvCapitalization, !Ref Environment, Capitalized]
      Schema:
        $schema: "http://json-schema.org/draft-04/schema#"
        type: "object"
        properties:
          data:
            type: "array"
            items:
              type: "object"
              properties:
                recipientId:
                  type: "string"
                  format: "uuid"
                address:
                  type: "object"
                  properties:
                    city:
                      type: "string"
                    country:
                      type: "string"
                    postalCode:
                      type: "string"
                    state:
                      type: "string"
                    street:
                      type: "string"
                  required: ["city", "country", "postalCode", "state", "street"]
                createdAt:
                  type: "string"
                  format: "date-time"
                firstName:
                  type: "string"
                lastName:
                  type: "string"
                description:
                  type: "string"
                occupation:
                  type: "string"
                organization:
                  type: "string"
                updatedAt:
                  type: "string"
                  format: "date-time"
              required: ["address", "createdAt", "firstName", "lastName", "recipientId", "updatedAt"]
          lastEvaluatedKey:
            type: "string"
          message:
            type: string
        required: ["data", "lastEvaluatedKey", "message"]

  # <------------------- GET Recipient By ID ------------------->

  RecipientByIdResponseModel:
    Type: AWS::ApiGateway::Model
    Properties:
      RestApiId: 
        Fn::ImportValue: 
          !Sub "one-hundred-letters-api-${Environment}"
      ContentType: "application/json"
      Name: !Sub 
        - "RecipientByIdResponseModel${CapitalizedEnv}"
        - CapitalizedEnv: !FindInMap [EnvCapitalization, !Ref Environment, Capitalized]
      Schema:
        $schema: "http://json-schema.org/draft-04/schema#"
        type: "object"
        properties:
          data:
            type: "object"
            properties:
              recipientId:
                type: "string"
                format: "uuid"
              address:
                type: "object"
                properties:
                  city:
                    type: "string"
                  country:
                    type: "string"
                  postalCode:
                    type: "string"
                  state:
                    type: "string"
                  street:
                    type: "string"
                required: ["city", "country", "postalCode", "state", "street"]
              createdAt:
                type: "string"
                format: "date-time"
              firstName:
                type: "string"
              lastName:
                type: "string"
              description:
                type: "string"
              occupation:
                type: "string"
              organization:
                type: "string"
              updatedAt:
                type: "string"
                format: "date-time"
            required: ["address", "firstName", "lastName", "recipientId"]
          message:
            type: string
        required: ["data", "message"]

  # <------------------- DELETE Recipients ------------------->

  RecipientDeleteResponseModel:
    Type: AWS::ApiGateway::Model
    Properties:
      RestApiId: 
        Fn::ImportValue: 
          !Sub "one-hundred-letters-api-${Environment}"
      ContentType: "application/json"
      Name: !Sub 
        - "RecipientDeleteResponseModel${CapitalizedEnv}"
        - CapitalizedEnv: !FindInMap [EnvCapitalization, !Ref Environment, Capitalized]
      Schema:
        $schema: "http://json-schema.org/draft-04/schema#"
        type: "object"
        properties:
          data:
            type: "object"
            properties:
              recipientId:
                type: "string"
                format: "uuid"
            required: ["recipientId"]
          message:
            type: "string"
        required: ["data", "message"]

Outputs:
  RecipientCreateRequestModelOutput:
    Value: !Ref RecipientCreateRequestModel
    Export:
      Name: !Sub recipient-create-request-model-${Environment}
  RecipientUpdateRequestModelOutput:
    Value: !Ref RecipientUpdateRequestModel
    Export:
      Name: !Sub recipient-update-request-model-${Environment}
  RecipientResponseModelOutput:
    Value: !Ref RecipientResponseModel
    Export:
      Name: !Sub recipient-response-model-${Environment}
  RecipientCreateResponseModelOutput:
    Value: !Ref RecipientCreateResponseModel
    Export:
      Name: !Sub recipient-create-response-model-${Environment}
  RecipientUpdateResponseModelOutput:
    Value: !Ref RecipientUpdateResponseModel
    Export:
      Name: !Sub recipient-update-response-model-${Environment}
  RecipientByIdResponseModelOutput:
    Value: !Ref RecipientByIdResponseModel
    Export:
      Name: !Sub recipient-by-id-response-model-${Environment}
  RecipientDeleteResponseModelOutput:
    Value: !Ref RecipientDeleteResponseModel
    Export:
      Name: !Sub recipient-delete-response-model-${Environment}
