AWSTemplateFormatVersion: '2010-09-09'

Resources:
  PersonTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "OneHundredLettersPersonTable"
      AttributeDefinitions:
        - AttributeName: "personId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "personId"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: "Name"
          Value: "OneHundredLettersPersonTable"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  CorrespondenceTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "OneHundredLettersCorrespondenceTable"
      AttributeDefinitions:
        - AttributeName: "correspondenceId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "correspondenceId"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: "Name"
          Value: "OneHundredLettersCorrespondenceTable"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  LetterTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "OneHundredLettersLetterTable"
      AttributeDefinitions:
        - AttributeName: "correspondenceId"
          AttributeType: "S"
        - AttributeName: "letterId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "correspondenceId"
          KeyType: "HASH"
        - AttributeName: "letterId"
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: "CorrespondenceIndex"
          KeySchema:
            - AttributeName: "correspondenceId"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"

Outputs:
  PersonTable:
    Value: !Ref PersonTable
    Description: "DynamoDB table for Person"
  CorrespondenceTable:
    Value: !Ref CorrespondenceTable
    Description: "DynamoDB table for Correspondence"
  LetterTable:
    Value: !Ref LetterTable
    Description: "DynamoDB table for Letter"
