AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Environment:
    Type: String
    Default: "dev"
    Description: "The environment for the deployment (dev or prod)"
    AllowedValues:
      - dev
      - prod
    ConstraintDescription: "Must be either 'dev' or 'prod'."
  CognitoUserPoolName:
    Type: String
    Default: "one-hundred-letters-user-pool"
  CognitoAppClientName:
    Type: String
    Default: "one-hundred-letters-app-client"

Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "${CognitoUserPoolName}-${Environment}"
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub "${CognitoAppClientName}-${Environment}"
      UserPoolId: !Ref CognitoUserPool
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_PASSWORD_AUTH

Outputs:
  CognitoUserPoolName:
    Description: "Name of the Cognito User Pool"
    Value: !Ref CognitoUserPoolName
    Export:
      Name: !Sub "${CognitoUserPoolName}-${Environment}"
