AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Environment:
    Type: String
    Default: "dev"
    Description: "The environment for the deployment (dev or prod)"
    AllowedValues:
      - dev
      - prod
    ConstraintDescription: "Must be either 'dev' or 'prod'."

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "one-hundred-letters-lambda-role-${Environment}"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaBasicExecution
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource:
                  - !Sub arn:aws:s3:::100-letters-project-api-${Environment}
                  - !Sub arn:aws:s3:::100-letters-project-client-images-${Environment}/*
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:BatchWriteItem
                  - dynamodb:Scan
                  - dynamodb:Query
                  - dynamodb:GetItem
                  - dynamodb:DeleteItem
                Resource:
                  - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/one-hundred-letters-recipient-table-${Environment}
                  - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/one-hundred-letters-recipient-table-${Environment}/index/LastNameIndex
                  - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/one-hundred-letters-correspondence-table-${Environment}
                  - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/one-hundred-letters-correspondence-table-${Environment}/index/RecipientIndex
                  - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/one-hundred-letters-correspondence-table-${Environment}/index/TitleIndex
                  - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/one-hundred-letters-letter-table-${Environment}
                  - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/one-hundred-letters-letter-table-${Environment}/index/CorrespondenceIndex
                  - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/one-hundred-letters-letter-table-${Environment}/index/LetterIndex
                  - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/one-hundred-letters-letter-table-${Environment}/index/TitleIndex

              - Effect: Allow
                Action:
                  - ses:SendEmail
                  - ses:SendRawEmail
                Resource: "*"

Outputs:
  LambdaExecutionRoleArn:
    Value: !GetAtt LambdaExecutionRole.Arn
    Description: "Lambda execution role ARN"
    Export:
      Name: !Sub "one-hundred-letters-lambda-role-${Environment}"
