AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Environment:
    Type: String
    Default: "dev"
    Description: "The environment for the deployment (dev or prod)"
    AllowedValues:
      - dev
      - prod
    ConstraintDescription: "Must be either 'dev' or 'prod'."

Resources:
  RecipientTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "one-hundred-letters-recipient-table-${Environment}"
      AttributeDefinitions:
        - AttributeName: "recipientId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "recipientId"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: "Name"
          Value: !Sub "one-hundred-letters-recipient-table-${Environment}"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
  CorrespondenceTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "one-hundred-letters-correspondence-table-${Environment}"
      AttributeDefinitions:
        - AttributeName: "correspondenceId"
          AttributeType: "S"
        - AttributeName: "recipientId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "correspondenceId"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: "RecipientIndex"
          KeySchema:
            - AttributeName: "recipientId"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
      Tags:
        - Key: "Name"
          Value: !Sub "one-hundred-letters-correspondence-table-${Environment}"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
  LetterTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "one-hundred-letters-letter-table-${Environment}"
      AttributeDefinitions:
        - AttributeName: "correspondenceId"
          AttributeType: "S"
        - AttributeName: "letterId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "correspondenceId"
          KeyType: "HASH"
        - AttributeName: "letterId"
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: "CorrespondenceIndex"
          KeySchema:
            - AttributeName: "correspondenceId"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
        - IndexName: "LetterIndex"
          KeySchema:
            - AttributeName: "letterId"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"

Outputs:
  RecipientTable:
    Value: !Ref RecipientTable
    Description: "DynamoDB table for Recipients"
    Export:
      Name: !Sub "one-hundred-letters-recipient-table-${Environment}"
  CorrespondenceTable:
    Value: !Ref CorrespondenceTable
    Description: "DynamoDB table for Correspondence"
    Export:
      Name: !Sub "one-hundred-letters-correspondence-table-${Environment}"
  LetterTable:
    Value: !Ref LetterTable
    Description: "DynamoDB table for Letters"
    Export:
      Name: !Sub "one-hundred-letters-letter-table-${Environment}"
