AWSTemplateFormatVersion: '2010-09-09'

Resources:
  PersonTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "OneHundredLettersPersonTable"
      AttributeDefinitions:
        - AttributeName: "PK"
          AttributeType: "S"
        - AttributeName: "SK"
          AttributeType: "S"
        - AttributeName: "lastName"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "PK"
          KeyType: "HASH"  # Primary Partition Key
        - AttributeName: "SK"
          KeyType: "RANGE" # Primary Sort Key
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      BillingMode: PROVISIONED
      Tags:
        - Key: "Name"
          Value: "OneHundredLettersPersonTable"
      GlobalSecondaryIndexes:
        - IndexName: "LastNameIndex"
          KeySchema:
            - AttributeName: "lastName"
              KeyType: "HASH"  # GSI Partition Key (lastName)
          Projection:
            ProjectionType: "ALL"  # Include all attributes in the index
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  CorrespondenceTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "OneHundredLettersCorrespondenceTable"
      AttributeDefinitions:
        - AttributeName: "PK"
          AttributeType: "S"
        - AttributeName: "SK"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "PK"
          KeyType: "HASH"
        - AttributeName: "SK"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      BillingMode: PROVISIONED
      Tags:
        - Key: "Name"
          Value: "OneHundredLettersCorrespondenceTable"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  LetterTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "OneHundredLettersLetterTable"
      AttributeDefinitions:
        - AttributeName: "PK"
          AttributeType: "S"
        - AttributeName: "SK"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "PK"
          KeyType: "HASH"
        - AttributeName: "SK"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      BillingMode: PROVISIONED
      Tags:
        - Key: "Name"
          Value: "OneHundredLettersLetterTable"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

Outputs:
  PersonTable:
    Value: !Ref PersonTable
    Description: "DynamoDB table for Person"
  CorrespondenceTable:
    Value: !Ref CorrespondenceTable
    Description: "DynamoDB table for Correspondence"
  LetterTable:
    Value: !Ref LetterTable
    Description: "DynamoDB table for Letter"
