AWSTemplateFormatVersion: '2010-09-09'

Resources:
  # <------------------- CREATE Recipient ------------------->

  RecipientCreateRequestModel:
    Type: AWS::ApiGateway::Model
    Properties:
      RestApiId: !ImportValue OneHundredLettersApi
      ContentType: "application/json"
      Name: "RecipientCreateModel"
      Schema:
        $schema: "http://json-schema.org/draft-04/schema#"
        type: "object"
        properties:
          address:
            type: "object"
            properties:
              city:
                type: "string"
              country:
                type: "string"
              postalCode:
                type: "string"
              state:
                type: "string"
              street:
                type: "string"
            required: ["city", "country", "postalCode", "state", "street"]
          firstName:
            type: "string"
          lastName:
            type: "string"
          description:
            type: "string"
          occupation:
            type: "string"
          organization:
            type: "string"
        required: ["address", "firstName", "lastName"]

  RecipientCreateResponseModel:
    Type: AWS::ApiGateway::Model
    Properties:
      RestApiId: !ImportValue OneHundredLettersApi
      ContentType: "application/json"
      Name: "RecipientCreateResponseModel"
      Schema:
        $schema: "http://json-schema.org/draft-04/schema#"
        type: "object"
        properties:
          data:
            type: "object"
            properties:
              recipientId:
                type: "string"
                format: "uuid"
              address:
                type: "object"
                properties:
                  city:
                    type: "string"
                  country:
                    type: "string"
                  postalCode:
                    type: "string"
                  state:
                    type: "string"
                  street:
                    type: "string"
                required: ["city", "country", "postalCode", "state", "street"]
              createdAt:
                type: "string"
                format: "date-time"
              firstName:
                type: "string"
              lastName:
                type: "string"
              description:
                type: "string"
              occupation:
                type: "string"
              organization:
                type: "string"
              updatedAt:
                type: "string"
                format: "date-time"
            required: ["address", "createdAt", "firstName", "lastName", "recipientId", "updatedAt"]
          message:
            type: string
        required: ["data", "message"]
        
  # <------------------- UPDATE Recipient ------------------->

  RecipientUpdateRequestModel:
    Type: AWS::ApiGateway::Model
    Properties:
      RestApiId: !ImportValue OneHundredLettersApi
      ContentType: "application/json"
      Name: "RecipientUpdateRequestModel"
      Schema:
        $schema: "http://json-schema.org/draft-04/schema#"
        type: "object"
        properties:
          recipientId:
            type: "string"
            format: "uuid"
          address:
            type: "object"
            properties:
              city:
                type: "string"
              country:
                type: "string"
              postalCode:
                type: "string"
              state:
                type: "string"
              street:
                type: "string"
            required: ["city", "country", "postalCode", "state", "street"]
          firstName:
            type: "string"
          lastName:
            type: "string"
          description:
            type: "string"
          occupation:
            type: "string"
          organization:
            type: "string"
        required: ["address", "firstName", "lastName", "recipientId"]

  RecipientUpdateResponseModel:
    Type: AWS::ApiGateway::Model
    Properties:
      RestApiId: !ImportValue OneHundredLettersApi
      ContentType: "application/json"
      Name: "RecipientUpdateResponseModel"
      Schema:
        $schema: "http://json-schema.org/draft-04/schema#"
        type: "object"
        properties:
          data:
            type: "object"
            properties:
              recipientId:
                type: "string"
                format: "uuid"
              address:
                type: "object"
                properties:
                  city:
                    type: "string"
                  country:
                    type: "string"
                  postalCode:
                    type: "string"
                  state:
                    type: "string"
                  street:
                    type: "string"
                required: ["city", "country", "postalCode", "state", "street"]
              createdAt:
                type: "string"
                format: "date-time"
              firstName:
                type: "string"
              lastName:
                type: "string"
              description:
                type: "string"
              occupation:
                type: "string"
              organization:
                type: "string"
              updatedAt:
                type: "string"
                format: "date-time"
            required: ["address", "createAt", "firstName", "lastName", "recipientId", "updatedAt"]
          message:
            type: string
        required: ["data", "message"]

  # <------------------- GET Recipients ------------------->

  RecipientResponseModel:
    Type: AWS::ApiGateway::Model
    Properties:
      RestApiId: !ImportValue OneHundredLettersApi
      ContentType: "application/json"
      Name: "RecipientResponseModel"
      Schema:
        $schema: "http://json-schema.org/draft-04/schema#"
        type: "object"
        properties:
          data:
            type: "array"
            items:
              type: "object"
              properties:
                recipientId:
                  type: "string"
                  format: "uuid"
                address:
                  type: "object"
                  properties:
                    city:
                      type: "string"
                    country:
                      type: "string"
                    postalCode:
                      type: "string"
                    state:
                      type: "string"
                    street:
                      type: "string"
                  required: ["city", "country", "postalCode", "state", "street"]
                createdAt:
                  type: "string"
                  format: "date-time"
                firstName:
                  type: "string"
                lastName:
                  type: "string"
                description:
                  type: "string"
                occupation:
                  type: "string"
                organization:
                  type: "string"
                updatedAt:
                  type: "string"
                  format: "date-time"
              required: ["address", "createdAt", "firstName", "lastName", "recipientId", "updatedAt"]
          lastEvaluatedKey:
            type: "string"
          message:
            type: string
        required: ["data", "lastEvaluatedKey", "message"]

  # <------------------- GET Recipient By ID ------------------->

  RecipientByIdResponseModel:
    Type: AWS::ApiGateway::Model
    Properties:
      RestApiId: !ImportValue OneHundredLettersApi
      ContentType: "application/json"
      Name: "RecipientByIdResponseModel"
      Schema:
        $schema: "http://json-schema.org/draft-04/schema#"
        type: "object"
        properties:
          data:
            type: "object"
            properties:
              recipientId:
                type: "string"
                format: "uuid"
              address:
                type: "object"
                properties:
                  city:
                    type: "string"
                  country:
                    type: "string"
                  postalCode:
                    type: "string"
                  state:
                    type: "string"
                  street:
                    type: "string"
                required: ["city", "country", "postalCode", "state", "street"]
              createdAt:
                type: "string"
                format: "date-time"
              firstName:
                type: "string"
              lastName:
                type: "string"
              description:
                type: "string"
              occupation:
                type: "string"
              organization:
                type: "string"
              updatedAt:
                type: "string"
                format: "date-time"
            required: ["address", "firstName", "lastName", "recipientId"]
          message:
            type: string
        required: ["data", "message"]

  # <------------------- DELETE Recipients ------------------->

  RecipientDeleteResponseModel:
    Type: AWS::ApiGateway::Model
    Properties:
      RestApiId: !ImportValue OneHundredLettersApi
      ContentType: "application/json"
      Name: "RecipientDeleteResponseModel"
      Schema:
        $schema: "http://json-schema.org/draft-04/schema#"
        type: "object"
        properties:
          data:
            type: "object"
            properties:
              recipientId:
                type: "string"
                format: "uuid"
            required: ["recipientId"]
          message:
            type: "string"
        required: ["data", "message"]

Outputs:
  RecipientCreateRequestModelOutput:
    Value: !Ref RecipientCreateRequestModel
    Export:
      Name: RecipientCreateRequestModel
  RecipientUpdateRequestModelOutput:
    Value: !Ref RecipientUpdateRequestModel
    Export:
      Name: RecipientUpdateRequestModel
  RecipientResponseModelOutput:
    Value: !Ref RecipientResponseModel
    Export:
      Name: RecipientResponseModel
  RecipientCreateResponseModelOutput:
    Value: !Ref RecipientCreateResponseModel
    Export:
      Name: RecipientCreateResponseModel
  RecipientUpdateResponseModelOutput:
    Value: !Ref RecipientUpdateResponseModel
    Export:
      Name: RecipientUpdateResponseModel
  RecipientByIdResponseModelOutput:
    Value: !Ref RecipientByIdResponseModel
    Export:
      Name: RecipientByIdResponseModel
  RecipientDeleteResponseModelOutput:
    Value: !Ref RecipientDeleteResponseModel
    Export:
      Name: RecipientDeleteResponseModel
