AWSTemplateFormatVersion: '2010-09-09'

Resources:
  CorrespondenceCreateRequestModel:
    Type: AWS::ApiGateway::Model
    Properties:
      RestApiId: !ImportValue OneHundredLettersApi
      ContentType: "application/json"
      Name: "CorrespondenceCreateModel"
      Schema:
        $schema: "http://json-schema.org/draft-04/schema#"
        type: "object"
        properties:
          correspondence:
            type: "object"
            properties:
              reason:
                type: "object"
                properties:
                  description:
                    type: "string"
                  domain:
                    type: "string"
                  impact:
                    type: "string"
                    enum: ["HIGH", "MEDIUM", "LOW"]
                required: ["description", "domain", "impact"]
              status:
                type: "string"
                enum: ["COMPLETED", "PENDING", "RESPONDED", "UNSENT"]
              title:
                type: "string"
            required: ["reason", "status", "title"]
          recipient:
            type: "object"
            properties:
              address:
                type: "object"
                properties:
                  city: 
                    type: "string"
                  country: 
                    type: "string"
                  postalCode:
                    type: "string"
                  state:
                    type: "string"
                  street:
                    type: "string"
              firstName:
                type: "string"
              lastName:
                type: "string"
              description:
                type: "string"
              occupation:
                type: "string"
              organization:
                type: "string"
            required: ["address", "firstName", "lastName"]
          letters:
            type: "array"
            items:
              type: "object"
              properties:
                date:
                  type: "string"
                  format: "date-time"
                description:
                  type: "string"
                imageURLs:
                  type: "array"
                  items:
                    type: "string"
                    format: "uri"
                method:
                  type: "string"
                  enum: ["TYPED", "HANDWRITTEN", "PRINTED", "DIGITAL", "OTHER"]
                receivedAt:
                  type: "string"
                sentAt:
                  type: "string"
                status:
                  type: "string"
                  enum: ["PENDING", "SENT", "RECEIVED", "RESPONDED"]
                text:
                  type: "string"
                title:
                  type: "string"
                type:
                  type: "string"
                  enum: ["MAIL", "EMAIL", "SMS", "OTHER"]
              required: ["date", "imageURLs", "method", "status", "text", "title", "type"]
        required: ["correspondence", "recipient", "letters"]
  
  CorrespondenceUpdateRequestModel:
    Type: AWS::ApiGateway::Model
    Properties:
      RestApiId: !ImportValue OneHundredLettersApi
      ContentType: "application/json"
      Name: "CorrespondenceUpdateModel"
      Schema:
        $schema: "http://json-schema.org/draft-04/schema#"
        type: "object"
        properties:
          correspondence:
            type: "object"
            properties:
              correspondenceId:
                type: "string"
              reason:
                type: "object"
                properties:
                  description:
                    type: "string"
                  domain:
                    type: "string"
                  impact:
                    type: "string"
                    enum: ["HIGH", "MEDIUM", "LOW"]
                required: ["description", "domain", "impact"]
              status:
                type: "string"
                enum: ["COMPLETED", "PENDING", "RESPONDED", "UNSENT"]
              title:
                type: "string"
            required: ["correspondenceId", "reason", "status", "title"]  # Moved here
          recipient:
            type: "object"
            properties:
              recipientId:
                type: "string"
              address:
                type: "object"
                properties:
                  city: 
                    type: "string"
                  country: 
                    type: "string"
                  postalCode:
                    type: "string"
                  state:
                    type: "string"
                  street:
                    type: "string"
              firstName:
                type: "string"
              lastName:
                type: "string"
              description:
                type: "string"
              occupation:
                type: "string"
              organization:
                type: "string"
            required: ["recipientId", "address", "firstName", "lastName"]
          letters:
            type: "array"
            items:
              type: "object"
              properties:
                letterId:
                  type: "string"
                date:
                  type: "string"
                  format: "date-time"
                description:
                  type: "string"
                imageURLs:
                  type: "array"
                  items:
                    type: "string"
                    format: "uri"
                method:
                  type: "string"
                  enum: ["TYPED", "HANDWRITTEN", "PRINTED", "DIGITAL", "OTHER"]
                receivedAt:
                  type: "string"
                sentAt:
                  type: "string"
                status:
                  type: "string"
                  enum: ["PENDING", "SENT", "RECEIVED", "RESPONDED"]
                text:
                  type: "string"
                title:
                  type: "string"
                type:
                  type: "string"
                  enum: ["MAIL", "EMAIL", "SMS", "OTHER"]
              required: ["date", "imageURLs", "letterId", "method", "status", "text", "title", "type"]
        required: ["correspondence", "recipient", "letters"]

Outputs:
  CorrespondenceCreateRequestModelOutput:
    Value: !Ref CorrespondenceCreateRequestModel
    Export:
      Name: CorrespondenceCreateRequestModel
  CorrespondenceUpdateRequestModelOutput:
    Value: !Ref CorrespondenceUpdateRequestModel
    Export:
      Name: CorrespondenceUpdateRequestModel