AWSTemplateFormatVersion: '2010-09-09'

Resources:
  PersonTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "OneHundredLettersPersonTable"
      AttributeDefinitions:
        - AttributeName: "personId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "personId"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      BillingMode: PROVISIONED
      Tags:
        - Key: "Name"
          Value: "OneHundredLettersPersonTable"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  CorrespondenceTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "OneHundredLettersCorrespondenceTable"
      AttributeDefinitions:
        - AttributeName: "correspondenceId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "correspondenceId"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      BillingMode: PROVISIONED
      Tags:
        - Key: "Name"
          Value: "OneHundredLettersCorrespondenceTable"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  LetterTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "OneHundredLettersLetterTable"
      AttributeDefinitions:
        - AttributeName: "letterId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "letterId"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      BillingMode: PROVISIONED
      Tags:
        - Key: "Name"
          Value: "OneHundredLettersLetterTable"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

Outputs:
  PersonTable:
    Value: !Ref PersonTable
    Description: "DynamoDB table for Person"
  CorrespondenceTable:
    Value: !Ref CorrespondenceTable
    Description: "DynamoDB table for Correspondence"
  LetterTable:
    Value: !Ref LetterTable
    Description: "DynamoDB table for Letter"
