AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  Environment:
    Type: String
    Description: "The environment for the deployment (dev or prod)"
    AllowedValues:
      - dev
      - prod
    Default: dev
    ConstraintDescription: "Must be either 'dev' or 'prod'."
  S3Key:
    Type: String
    Description: The S3 key for the lambda function zip file.

Resources:
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "sendContactEmail-${Environment}"
      Runtime: nodejs20.x
      Role:
        Fn::ImportValue: 
            !Sub "one-hundred-letters-lambda-role-${Environment}"
      Handler: routes/sendContactEmail/index.handler
      Code:
        S3Bucket:
          Fn::ImportValue: 
            !Sub "100-letters-project-api-${Environment}"
        S3Key: !Ref S3Key
      Timeout: 10
      MemorySize: 128
      Environment:
        Variables:
          ACCESS_CONTROL_ALLOW_ORIGIN: !Sub "{{resolve:secretsmanager:one-hundred-letters-api-${Environment}:SecretString:accessControlAllowOrigin}}"
          CORRESPONDENCE_TABLE_NAME: !Sub "{{resolve:secretsmanager:one-hundred-letters-tables-${Environment}:SecretString:correspondenceTableName}}"
          ENVIRONMENT: !Ref Environment
          LETTER_TABLE_NAME: !Sub "{{resolve:secretsmanager:one-hundred-letters-tables-${Environment}:SecretString:letterTableName}}"
          RECAPTCHA_SECRET_KEY: !Sub "{{resolve:secretsmanager:one-hundred-letters-ses-${Environment}:SecretString:recaptchaSecretKey}}"
          RECIPIENT_TABLE_NAME: !Sub "{{resolve:secretsmanager:one-hundred-letters-tables-${Environment}:SecretString:recipientTableName}}"
          SES_SOURCE: !Sub "{{resolve:secretsmanager:one-hundred-letters-ses-${Environment}:SecretString:sesSource}}"
          SES_CONTACT: !Sub "{{resolve:secretsmanager:one-hundred-letters-ses-${Environment}:SecretString:sesContact}}"

  LambdaInvokePermissionGetRecipientById:
    Type: AWS::Lambda::Permission
    DependsOn: MyLambdaFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:sendContactEmail-${Environment}"
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/POST/*"
