name: Deploy API Gateway

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Development environment"
        required: true
        type: choice
        options:
          - dev
          - prod

jobs:
  deploy-gateway:
    name: Deploy API Gateway Stage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Deploy API Gateway Stage
        run: |
          if [ "${{ github.event.inputs.environment }}" == "prod" ]; then
            API_ID="${{ secrets.API_GATEWAY_ID_PROD }}"
          else
            API_ID="${{ secrets.API_GATEWAY_ID_DEV }}"
          fi
          STAGE_NAME="${{ github.event.inputs.environment }}"
          set -e
          
          DEPLOYMENT_ID=$(aws apigateway create-deployment \
            --rest-api-id $API_ID \
            --stage-name $STAGE_NAME \
            --region us-west-2 \
            --query 'id' \
            --output text) || {
              echo "Deployment creation failed..."
              exit 1
            }

          echo "Deployment created successfully with ID: $DEPLOYMENT_ID"
