name: Deploy Lambda Automatically

on:
  push:
    branches:
      - main  # Or the branch you want to deploy from

jobs:
  deploy-lambdas:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsRole
          role-session-name: GithubLambdaDeployment
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-duration-seconds: 3600

      - name: Check for changes in Lambda source code
        id: check_diff
        run: |
          changed_functions=""
          # Fetch the latest changes from the remote repository
          git fetch origin

          # Loop over all Lambda function directories (adjust as necessary)
          for FUNCTION_NAME in createCorrespondence getCorrespondences getCorrespondencesById getRecipientById getRecipients updateCorrespondence; do
            # Check if there are any changes in the respective Lambda function folder compared to main
            if git diff --quiet origin/main -- routes/$FUNCTION_NAME; then
              echo "No changes detected in $FUNCTION_NAME"
            else
              echo "Changes detected in $FUNCTION_NAME"
              changed_functions="$changed_functions $FUNCTION_NAME"
            fi
          done

          if [ -z "$changed_functions" ]; then
            echo "No Lambda function changes detected. Skipping deployment."
            exit 0
          fi

          # Export changed functions list for later steps
          echo "Changed functions: $changed_functions"
          echo "changed_functions=$changed_functions" >> $GITHUB_ENV

      - name: Build, package, and deploy Lambda functions
        run: |
          for FUNCTION_NAME in ${{ env.changed_functions }}; do
            echo "Processing Lambda function: $FUNCTION_NAME"
            
            # Check if Lambda function exists
            FUNCTION_EXISTS=$(aws lambda get-function --function-name "$FUNCTION_NAME" --query "Configuration.FunctionName" --output text)
            if [ "$FUNCTION_EXISTS" != "None" ]; then
              echo "Function $FUNCTION_NAME exists, ready for update."
            else
              echo "Function $FUNCTION_NAME not found, creating it..."
            fi

            # Build and package the Lambda function
            cd routes/$FUNCTION_NAME
            npm install
            npm run build
            npm run package
            cd ../../  # Go back to root directory

            # Upload Lambda package to S3
            aws s3 cp "routes/$FUNCTION_NAME/dist/$FUNCTION_NAME.zip" "s3://100-letters-project-api/$FUNCTION_NAME.zip"

            # Deploy or create Lambda function
            if [ "$FUNCTION_EXISTS" != "None" ]; then
              echo "Updating Lambda function: $FUNCTION_NAME"
              aws lambda update-function-code --function-name "$FUNCTION_NAME" --s3-bucket 100-letters-project-api --s3-key "$FUNCTION_NAME.zip"
            else
              echo "Creating Lambda function: $FUNCTION_NAME"
              aws lambda create-function --function-name "$FUNCTION_NAME" \
                --runtime nodejs20.x \
                --role arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsRole \
                --handler index.handler \
                --code S3Bucket=100-letters-project-api,S3Key=$FUNCTION_NAME.zip \
                --region us-west-2
            fi
          done
