name: Deploy Lambda Manually

on:
  workflow_dispatch:
    inputs:
      lambda_function:
        description: "Select a Lambda function to deploy..."
        required: true
        type: choice
        options:
          - createCorrespondence
          - deleteCorrespondence
          - getCorrespondences
          - getCorrespondencesById
          - getRecipientById
          - getRecipients
          - updateCorrespondence

jobs:
  deploy-lambda:
    name: Deploy Lambda Manually
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsRole
          role-session-name: GithubLambdaDeployment
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-duration-seconds: 3600

      - name: Build & Package Lambda
        run: |
          FUNCTION_NAME="${{ github.event.inputs.lambda_function }}"
          cd routes/$FUNCTION_NAME
          npm install
          npm run build
          npm run package
          cd ../../  # Go back to root directory

      - name: Upload Lambda to S3
        run: |
          FUNCTION_NAME="${{ github.event.inputs.lambda_function }}"
          aws s3 cp "routes/$FUNCTION_NAME/dist/$FUNCTION_NAME.zip" "s3://100-letters-project-api/$FUNCTION_NAME.zip"

      - name: Deploy Lambda - Run Change Set
        uses: aws-actions/aws-lambda-deploy@v2
        with:
          function-name: "${{ github.event.inputs.lambda_function }}"
          s3-bucket: "100-letters-project-api"
          s3-key: "${{ github.event.inputs.lambda_function }}.zip"
          region: us-west-2
