name: Deploy All Lambdas

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Development environment"
        required: true
        type: choice
        options:
          - dev
          - prod

jobs:
  trigger-deployments:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Get Lambda Names
        id: list_lambdas
        run: |
          lambdas=()
          for dir in src/routes/*; do
            if [ -d "$dir" ]; then
              if [ -f "$dir/package.json" ]; then
                lambda_name=$(jq -r '.name' "$dir/package.json")
                if [ "$lambda_name" != "null" ]; then
                  lambdas+=("$lambda_name")
                fi
              fi
            fi
          done
          echo "LAMBDA_NAMES=${lambdas[@]}" >> $GITHUB_ENV

      - name: Deploy All Lambdas
        run: |
          IFS=' ' read -r -a lambdas <<< "$LAMBDA_NAMES"
          environment="${{ github.event.inputs.environment }}"
          for lambda in "${lambdas[@]}"; do
            echo "Deploying $lambda with environment $environment..."
            curl -X POST https://api.github.com/repos/${{ github.repository }}/actions/workflows/manual.yml/dispatches \
              -H "Authorization: Bearer ${{ secrets.ACTIONS_PAT }}" \
              -d '{"ref":"${{ github.ref }}","inputs":{"lambda_function":"'"$lambda"'","environment":"'"$environment"'"}}'
          done
