name: Deploy Lambda Manually

on:
  workflow_dispatch:
    inputs:
      lambda_function:
        description: "Select a Lambda function to deploy"
        required: true
        type: choice
        options:
          - createCorrespondence
          - getCorrespondences
          - getCorrespondencesById
          - getRecipientById
          - getRecipients
          - updateCorrespondence

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsRole
          role-session-name: GithubLambdaDeployment
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-duration-seconds: 3600

      - name: Check if Lambda function exists
        id: check_lambda
        run: |
          FUNCTION_NAME="${{ github.event.inputs.lambda_function }}"
          echo "Checking if Lambda function exists: $FUNCTION_NAME"
          if aws lambda get-function --function-name "$FUNCTION_NAME"; then
            echo "Function $FUNCTION_NAME exists, ready for update."
            echo "exists=true" >> $GITHUB_ENV
          else
            echo "Function $FUNCTION_NAME not found, creating it..."
            echo "exists=false" >> $GITHUB_ENV
          fi

      - name: Build and package Lambda function
        run: |
          FUNCTION_NAME="${{ github.event.inputs.lambda_function }}"
          cd routes/$FUNCTION_NAME
          npm install
          npm run build
          npm run package
          ls -R dist
          cd ../../  # Go back to root directory

      - name: Upload Lambda package to S3
        run: |
          FUNCTION_NAME="${{ github.event.inputs.lambda_function }}"
          aws s3 cp "routes/$FUNCTION_NAME/dist/$FUNCTION_NAME.zip" "s3://100-letters-project-api/routes/$FUNCTION_NAME.zip"
      
      - name: Deploy or create Lambda function
        run: |
          FUNCTION_NAME="${{ github.event.inputs.lambda_function }}"
          if [ "$exists" == "true" ]; then
            echo "Updating Lambda function: $FUNCTION_NAME"
            aws lambda update-function-code --function-name "$FUNCTION_NAME" --s3-bucket 100-letters-project-api --s3-key "routes/$FUNCTION_NAME.zip"
          else
            echo "Creating Lambda function: $FUNCTION_NAME"
            aws lambda create-function --function-name "$FUNCTION_NAME" \
              --runtime nodejs20.x \
              --role arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsRole \
              --handler index.handler \
              --code S3Bucket=100-letters-project-api,S3Key=routes/$FUNCTION_NAME.zip \
              --region us-west-2
          fi
