name: Rollback

on:
  workflow_dispatch:
    inputs:
      lambda_function:
        description: "Lambda function name"
        required: true
        type: choice
        options:
          - createCorrespondence
          - createLetter
          - createRecipient
          - deleteCorrespondence
          - deleteLetter
          - deleteRecipient
          - deleteUpload
          - getCorrespondences
          - getCorrespondenceById
          - getLetterById
          - getLetters
          - getRecipientById
          - getRecipients
          - sendContactEmail
          - updateCorrespondence
          - updateLetter
          - updateRecipient
          - uploads
      s3_zip_file:
        description: "Zip file name in S3 (e.g., previous.zip)"
        required: true
        type: string
      environment:
        description: "Development environment"
        required: true
        type: choice
        options:
          - dev
          - prod

jobs:
  rollback-lambda:
    name: Rollback Lambda - ${{ github.event.inputs.lambda_function }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Check Change Set Update/Create 
        id: change_set_type
        run: |
          STACK_NAME="one-hundred-letters-route-${{ github.event.inputs.lambda_function }}-stack-${{ github.event.inputs.environment }}"
          if aws cloudformation describe-stacks --stack-name "$STACK_NAME" --region us-west-2 >/dev/null 2>&1; then
            echo "Updating change set..."
            echo "change_set_type=UPDATE" >> $GITHUB_ENV
          else
            echo "Creating change set..."
            echo "change_set_type=CREATE" >> $GITHUB_ENV
          fi

      - name: Check Stack Status
        id: stack_status
        if: env.change_set_type == 'UPDATE'
        run: |
          STACK_NAME="one-hundred-letters-route-${{ github.event.inputs.lambda_function }}-stack-${{ github.event.inputs.environment }}"
          STATUS=$(aws cloudformation describe-stacks --stack-name "$STACK_NAME" --query "Stacks[0].StackStatus" --output text 2>/dev/null || echo "NOT_FOUND")
          echo "Status: $STATUS"
          FAILED_STATES=("CREATE_FAILED" "ROLLBACK_FAILED" "UPDATE_FAILED" "DELETE_FAILED" "UPDATE_ROLLBACK_FAILED" "UPDATE_ROLLBACK_COMPLETE" "ROLLBACK_COMPLETE")
          if [[ " ${FAILED_STATES[@]} " =~ " ${STATUS} " ]]; then
            echo "Deleting stack due to status..."
            aws cloudformation delete-stack --stack-name "$STACK_NAME" --region us-west-2
            echo "Waiting for stack deletion to complete..."
            aws cloudformation wait stack-delete-complete --stack-name "$STACK_NAME" --region us-west-2
            echo "Stack deleted successfully!"
            echo "change_set_type=CREATE" >> $GITHUB_ENV
          fi

      - name: Create CloudFormation Change Set
        run: |
          FUNCTION_NAME="${{ github.event.inputs.lambda_function }}"
          STACK_NAME="one-hundred-letters-route-${{ github.event.inputs.lambda_function }}-stack-${{ github.event.inputs.environment }}"
          TEMPLATE_FILE="src/routes/${{ github.event.inputs.lambda_function }}/template.yaml"
          CHANGE_SET_NAME="rollback-${{ github.event.inputs.lambda_function }}-change-set-${{ github.event.inputs.environment }}"
          CHANGE_SET_TYPE="${{ env.change_set_type }}"
          S3_BUCKET="100-letters-project-api-${{ github.event.inputs.environment }}"
          S3_KEY="${{ github.event.inputs.lambda_function }}/${{ github.event.inputs.s3_zip_file }}"
          aws cloudformation create-change-set \
            --stack-name $STACK_NAME \
            --template-body file://$TEMPLATE_FILE \
            --parameters ParameterKey=S3Key,ParameterValue=$S3_KEY \
            --change-set-name $CHANGE_SET_NAME \
            --change-set-type $CHANGE_SET_TYPE \
            --capabilities CAPABILITY_NAMED_IAM \
            --region us-west-2
          echo "Waiting for change set to be created..."
          aws cloudformation wait change-set-create-complete \
            --stack-name $STACK_NAME \
            --change-set-name $CHANGE_SET_NAME \
            --region us-west-2

      - name: Execute CloudFormation Change Set
        run: |
          STACK_NAME="one-hundred-letters-route-${{ github.event.inputs.lambda_function }}-stack-${{ github.event.inputs.environment }}"
          CHANGE_SET_NAME="rollback-${{ github.event.inputs.lambda_function }}-change-set-${{ github.event.inputs.environment }}"
          aws cloudformation execute-change-set \
            --stack-name $STACK_NAME \
            --change-set-name $CHANGE_SET_NAME \
            --region us-west-2

      - name: Monitor CloudFormation Stack Status
        run: |
          DONE_STATUSES=("CREATE_COMPLETE" "UPDATE_COMPLETE" "ROLLBACK_COMPLETE" "UPDATE_ROLLBACK_COMPLETE" "DELETE_COMPLETE")
          FAILED_STATUSES=("CREATE_FAILED" "UPDATE_FAILED" "ROLLBACK_FAILED" "DELETE_FAILED" "UPDATE_ROLLBACK_FAILED" "ROLLBACK_IN_PROGRESS" "DELETE_IN_PROGRESS")
          STACK_NAME="one-hundred-letters-route-${{ github.event.inputs.lambda_function }}-stack-${{ github.event.inputs.environment }}"
          MAX_RETRIES=30
          RETRY_COUNT=0
          while true; do
            STATUS=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --region us-west-2 --query "Stacks[0].StackStatus" --output text)
            echo "Status: $STATUS"
            if [[ " ${DONE_STATUSES[@]} " =~ " ${STATUS} " ]]; then
              echo "Rollback completed successfully!"
              exit 0
            elif [[ " ${FAILED_STATUSES[@]} " =~ " ${STATUS} " ]]; then
              echo "Rollback failed!"
              exit 1
            fi
            RETRY_COUNT=$((RETRY_COUNT + 1))
            if [[ $RETRY_COUNT -ge $MAX_RETRIES ]]; then
              echo "Max retries reached, exiting."
              exit 1
            fi
            sleep 10
          done
